require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhcfmsController do

  # This should return the minimal set of attributes required to create a valid
  # Phcfm. As you add validations to Phcfm, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhcfmsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all phcfms as @phcfms" do
      phcfm = Phcfm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:phcfms).should eq([phcfm])
    end
  end

  describe "GET show" do
    it "assigns the requested phcfm as @phcfm" do
      phcfm = Phcfm.create! valid_attributes
      get :show, {:id => phcfm.to_param}, valid_session
      assigns(:phcfm).should eq(phcfm)
    end
  end

  describe "GET new" do
    it "assigns a new phcfm as @phcfm" do
      get :new, {}, valid_session
      assigns(:phcfm).should be_a_new(Phcfm)
    end
  end

  describe "GET edit" do
    it "assigns the requested phcfm as @phcfm" do
      phcfm = Phcfm.create! valid_attributes
      get :edit, {:id => phcfm.to_param}, valid_session
      assigns(:phcfm).should eq(phcfm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Phcfm" do
        expect {
          post :create, {:phcfm => valid_attributes}, valid_session
        }.to change(Phcfm, :count).by(1)
      end

      it "assigns a newly created phcfm as @phcfm" do
        post :create, {:phcfm => valid_attributes}, valid_session
        assigns(:phcfm).should be_a(Phcfm)
        assigns(:phcfm).should be_persisted
      end

      it "redirects to the created phcfm" do
        post :create, {:phcfm => valid_attributes}, valid_session
        response.should redirect_to(Phcfm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phcfm as @phcfm" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phcfm.any_instance.stub(:save).and_return(false)
        post :create, {:phcfm => {}}, valid_session
        assigns(:phcfm).should be_a_new(Phcfm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phcfm.any_instance.stub(:save).and_return(false)
        post :create, {:phcfm => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phcfm" do
        phcfm = Phcfm.create! valid_attributes
        # Assuming there are no other phcfms in the database, this
        # specifies that the Phcfm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Phcfm.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => phcfm.to_param, :phcfm => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested phcfm as @phcfm" do
        phcfm = Phcfm.create! valid_attributes
        put :update, {:id => phcfm.to_param, :phcfm => valid_attributes}, valid_session
        assigns(:phcfm).should eq(phcfm)
      end

      it "redirects to the phcfm" do
        phcfm = Phcfm.create! valid_attributes
        put :update, {:id => phcfm.to_param, :phcfm => valid_attributes}, valid_session
        response.should redirect_to(phcfm)
      end
    end

    describe "with invalid params" do
      it "assigns the phcfm as @phcfm" do
        phcfm = Phcfm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phcfm.any_instance.stub(:save).and_return(false)
        put :update, {:id => phcfm.to_param, :phcfm => {}}, valid_session
        assigns(:phcfm).should eq(phcfm)
      end

      it "re-renders the 'edit' template" do
        phcfm = Phcfm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phcfm.any_instance.stub(:save).and_return(false)
        put :update, {:id => phcfm.to_param, :phcfm => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phcfm" do
      phcfm = Phcfm.create! valid_attributes
      expect {
        delete :destroy, {:id => phcfm.to_param}, valid_session
      }.to change(Phcfm, :count).by(-1)
    end

    it "redirects to the phcfms list" do
      phcfm = Phcfm.create! valid_attributes
      delete :destroy, {:id => phcfm.to_param}, valid_session
      response.should redirect_to(phcfms_url)
    end
  end

end
